#docker-compose up -d
version: '3'
services:
  gateway:
    image: app-gateway
    environment:

      - SPRING_CLOUD_CONFIG_URI=http://spring-cloud-config-server:8081 # ajusta según la ubicación de tu servidor de configuración
    ports:
      - "8080:8080"
    # Otros parámetros de configuración para tu gateway

  spring-cloud-config-server:
    image: config-service
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/dennisyaj/config-data.git
    volumes:
      - /path/to/local/config:/path/to/local/config # monta la ubicación de tu configuración local
    # Otros parámetros de configuración para tu servidor de configuración

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    # Otros parámetros de configuración para Consul

  app-authors-service:
    image: app-authors
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://spring-cloud-config-server:8081 # ajusta según la ubicación de tu servidor de configuración
    deploy:
      replicas: 1
    expose:
      - 9090
    depends_on:
      - consul
      - gateway
    # Otros parámetros de configuración para tu servicio de autores

  app-books-service:
    image: app-books
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://spring-cloud-config-server:8081 # ajusta según la ubicación de tu servidor de configuración
      - APP_AUTHORS_URL=http://gateway/app-authors # ajusta según la ubicación de tu gateway
    deploy:
      replicas: 1
    expose:
      - 7070
    depends_on:
      - consul
      - gateway
      - app-authors-service
    # Otros parámetros de configuración para tu servicio de libros
