server:
  port: 8082

#Consul

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: posts-route
            uri: ${POST_ROUTE_URI:http://localhost:9090}
            predicates:
              - Path=/authors/**
            filters:
              - PrefixPath=/api
              - AddResponseHeader=X-Powered-By, Gateway Service
